apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-myapp-ingress
  namespace: default

spec:
  rules:
  - host: nginx-from-argocd.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-myapp-expose-service
            port:
              number: 8080
