apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-3
  annotations:
    # argocd.argoproj.io/sync-options: Force=true,Replace=true
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 1  # Retry the job if it fails, up to 3 times
  template:
    spec:
      containers:
      - name: test-container
        image: ivantws23/inst-win
        command: ["sh", "-c", "echo 'test done'"]
      restartPolicy: Never