apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 1  # Retry the job if it fails, up to 3 times
  template:
    spec:
      containers:
      - name: test-container
        image: ivantws23/inst-win
        env:
        - name: ASSETS_VERSION
          value: "v.1.2.3.4"
        command: ["sh", "-c", "echo 'test done'"]
      securityContext:
        runAsUser: 0  # Run as root
        runAsGroup: 0  # Root group
      restartPolicy: Never