apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-file-job
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: fetch-file-container
        image: curlimages/curl:7.78.0  # Using a minimal curl image
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            curl -o /mnt/data/fox.jpg https://i.pinimg.com/originals/67/f9/2e/67f92e258297942f00aab9f31706e353.jpg && echo "Fox image file downloaded to PV."
        volumeMounts:
        - name: storage
          mountPath: /mnt/data  # Mount point for the PV inside this container - the cURL one ..
      restartPolicy: Never
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: pvc-example
